namespace: community
name: grafana
version: 1.6.1
readme: README.md
authors:
  - Rémi REY (@rrey)
  - Thierry Sallé (@seuf)
description: Collection allowing to interact with Grafana APIs
license_file: LICENSE
tags:
  - monitoring
  - grafana
dependencies: {}
repository: https://github.com/ansible-collections/community.grafana.git
documentation: https://docs.ansible.com/ansible/latest/collections/community/grafana/
homepage: https://github.com/ansible-collections/grafana
issues: https://github.com/ansible-collections/community.grafana/issues
