namespace: community
name: grafana
version: 0.2.2
readme: README.md
authors:
- Rémi REY (@rrey)
- Thierry Sallé (@seuf)
description: Collection allowing to interact with Grafana APIs
license_file: LICENSE
tags:
  - monitoring
  - grafana
dependencies: {}
repository: https://github.com/ansible-collections/grafana.git
documentation: https://github.com/ansible-collections/grafana.git
homepage: https://github.com/ansible-collections/grafana
issues: https://github.com/ansible-collections/grafana/issues
