FROM prom/prometheus:latest

COPY web.yml /etc/prometheus/web.yml

CMD [ \
    "--config.file=/etc/prometheus/prometheus.yml", \
    "--storage.tsdb.path=/prometheus",\
    "--web.console.libraries=/usr/share/prometheus/console_libraries", \
    "--web.console.templates=/usr/share/prometheus/consoles", \
    "--web.config.file=/etc/prometheus/web.yml" \
    ] 
