---
# datasource.0 = grafana_datasource attribute
- name: manage datasource
  community.grafana.grafana_datasource:
    url: "{{ grafana_url }}"
    url_username: "{{ grafana_username }}"
    url_password:  "{{ grafana_password }}"
    tls_skip_verify: "{{ datasource.0.tls_skip_verify | default(omit) }}"
    org_id: "{{ datasource.0.org_id | default(omit) }}"
    name: "{{ datasource.0.name }}"
    ds_type: "{{ datasource.0.ds_type | default(omit) }}"
    access: "{{ datasource.0.access | default(omit) }}"
    ds_url: "{{ datasource.0.ds_url | default(omit) }}"
    database: "{{ datasource.0.database | default(omit) }}"
    with_credentials: "{{ datasource.0.with_credentials | default(omit) }}"
    is_default: "{{ datasource.0.is_default | default(omit) }}"
    user: "{{ datasource.0.user | default(omit) }}"
    password: "{{ datasource.0.password | default(omit) }}"
    additional_json_data: "{{ datasource.0.additional_json_data | default(omit) }}"
    additional_secure_json_data: "{{ datasource.0.additional_secure_json_data | default(omit) }}"
  loop: "{{ grafana_datasources |subelements('datasource_object') }}"
  loop_control:
    loop_var: datasource
  tags: datasource
