---
- name: manage team
  community.grafana.grafana_team:
    url: "{{ grafana_url }}"
    url_username: "{{ grafana_username }}"
    url_password:  "{{ grafana_password }}"
    name: "{{ team.1 }}"
    email: "{{ team.0.email }}"
    members: "{{ team.0.members | default(omit) }}"
    state: "{{ team.0.state | default(omit) }}"
    enforce_members: "{{ team.0.enforce_members | default(omit) }}"
    skip_version_check: "{{ team.0.skip_version_check | default(omit) }}"
  loop: "{{ grafana_teams|subelements('team_object') }}"
  loop_control:
    loop_var: team
  tags: team
