---
- name: Converge
  hosts: localhost
  environment:
    http_proxy: "{{ lookup('env', 'HTTP_PROXY') | default(omit)  }}"
    https_proxy: "{{ lookup('env', 'HTTPS_PROXY') | default(omit) }}"
    no_proxy: "{{ lookup('env', 'NO_PROXY') | default(omit) }}"
  tasks:
    - name: Include ansible-role-grafana
      ansible.builtin.include_role:
        name: ansible-role-grafana
  vars:
    grafana_url: http://localhost:3000
    grafana_username: admin
    grafana_password: admin

    grafana_datasources:
      - name: Loki
        ds_type: loki
        ds_url: http://127.0.0.1:3100
        tls_skip_verify: true

    grafana_folders:
      - name: my_service
      - name: other_service

    grafana_dashboards:
      - folder: my_service
        uid: ES5apb27k
        path: test_dashboard.json
        overwrite: true
