---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: rndmh3ro/docker-debian11-ansible:latest
    command: ${MOLECULE_DOCKER_COMMAND:-/lib/systemd/systemd}
    env:
      container: docker
    pre_build_image: true
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callback_whitelist: profile_tasks, timer, yaml
verifier:
  name: ansible
