name: Check Grafana Releases

on:
  schedule:
    - cron:  '0 1 * * 0'

permissions:
  contents: read
  pull-requests: write

jobs:
  check_grafana_releases:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python_version }}
        uses: actions/setup-python@v2

      - name: Install ansible
        run: pip install -r hacking/requirements.txt

      - name: Get the latest major releases of Grafana and update repo
        run: |
          RELEASES_LIST="$(python3 hacking/find_grafana_versions.py)"
          sed -i "s/grafana_version:.*/grafana_version: $RELEASES_LIST/" .github/workflows/ansible-test.yml README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v4
        with:
            token: ${{ secrets.RREY_PAT }}
            commit-message: Update tested Grafana versions
            title: Bump Grafana versions
            branch: auto-bump-grafana
            reviewers: rrey
            base: main
