name: Check and Update Grafana Releases

on:
  schedule:
    - cron: '0 1 * * 0'
  workflow_dispatch:

permissions:
  contents: write
  pull-requests: write

jobs:
  check_and_update_releases:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5

      - name: Install requirements
        run: pip install -r hacking/requirements.txt

      - name: Get the latest major releases of Grafana and update repo
        run: |
          RELEASES_LIST="$(python3 hacking/find_grafana_versions.py)"
          sed -i "s/grafana_version:.*/grafana_version: $RELEASES_LIST/" .github/workflows/ansible-test.yml README.md

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.RREY_PAT }}
          commit-message: "ci(deps): bump grafana versions"
          title: "ci(deps): bump grafana versions"
          branch: auto-bump-grafana
          base: main
