---
name: Publish to Ansible Galaxy

on:
  release:
    types:
      - published

jobs:
  release:
    name: ansible galaxy
    runs-on: ubuntu-latest
    steps:
      - name: galaxy
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
