---
name: Publish to Ansible Galaxy

on:
  push:
    tags:
      - '*'

jobs:
  release:
    name: ansible galaxy
    runs-on: ubuntu-latest
    steps:
      - name: Check out the codebase.
        uses: actions/checkout@v2

      - name: galaxy
        uses: robertdebock/galaxy-action@1.1.0
        with:
          galaxy_api_key: ${{ secrets.GALAXY_API_KEY }}
